"""empty message

Revision ID: cd30891809c3
Revises: 
Create Date: 2021-04-19 21:42:29.270688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd30891809c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gender')),
    sa.UniqueConstraint('name', name=op.f('uq_gender_name'))
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login')),
    sa.UniqueConstraint('email', name=op.f('uq_login_email'))
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('nat', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('picture', sa.String(length=250), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], name=op.f('fk_account_gender_id_gender')),
    sa.ForeignKeyConstraint(['login_id'], ['login.id'], name=op.f('fk_account_login_id_login')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=30), nullable=False),
    sa.Column('postal', sa.String(length=10), nullable=False),
    sa.Column('number', sa.String(length=7), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_address_account_id_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_table('account')
    op.drop_table('login')
    op.drop_table('gender')
    # ### end Alembic commands ###
